// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]
#![allow(clippy::module_inception)]

macro_rules! __rqb_relation_wrapper {
    () => {
        #[derive(Clone, Debug)]
        pub struct Relation {
            inner: rqb::prelude::Relation,
        }

        impl Relation {
            fn new(dataset: Dataset) -> Self {
                Self {
                    inner: rqb::prelude::Relation::new(dataset),
                }
            }

            pub fn alias(mut self, alias: impl Into<String>) -> Self {
                self.inner = self.inner.alias(alias);
                self
            }

            pub fn dataset(&self) -> Dataset {
                self.inner.dataset().clone()
            }
        }

        impl From<Relation> for Dataset {
            fn from(value: Relation) -> Self {
                value.inner.into()
            }
        }

        impl From<&Relation> for Dataset {
            fn from(value: &Relation) -> Self {
                value.dataset()
            }
        }
    };
}

macro_rules! __rqb_relation {
    (
        table,
        $schema:literal,
        $source:literal,
        [$(($const_name:ident, $field_expr:expr, $method_name:ident)),* $(,)?]
    ) => {
        use rqb::prelude::*;

        $(pub const $const_name: Field = $field_expr;)*

        pub const FIELDS: &[Field] = &[$($const_name),*];

        pub fn dataset() -> Dataset {
            Dataset::new_static($source, rqb::Source::static_table($source).schema($schema))
                .static_fields(FIELDS)
        }

        pub fn table() -> Relation {
            Relation::new(dataset())
        }

        __rqb_relation_wrapper!();

        impl Relation {
            $(
                pub fn $method_name(&self) -> FieldRef {
                    self.inner.field($const_name)
                }
            )*
        }
    };
    (
        view,
        $schema:literal,
        $source:literal,
        [$(($const_name:ident, $field_expr:expr, $method_name:ident)),* $(,)?]
    ) => {
        use rqb::prelude::*;

        $(pub const $const_name: Field = $field_expr;)*

        pub const FIELDS: &[Field] = &[$($const_name),*];

        pub fn dataset() -> Dataset {
            Dataset::new_static($source, rqb::Source::static_view($source).schema($schema))
                .static_fields(FIELDS)
        }

        pub fn view() -> Relation {
            Relation::new(dataset())
        }

        __rqb_relation_wrapper!();

        impl Relation {
            $(
                pub fn $method_name(&self) -> FieldRef {
                    self.inner.field($const_name)
                }
            )*
        }
    };
}

pub mod enums {
    use rqb::prelude::*;
    pub const ORDER_STATUS: EnumType = EnumType::new(
        Some("public"),
        "order_status",
        &["draft", "paid", "cancelled", "refunded"],
    );
    #[derive(Clone, Copy, Debug, PartialEq, Eq, rqb::serde::Serialize, rqb::serde::Deserialize)]
    #[serde(crate = "rqb::serde")]
    pub enum OrderStatus {
        #[serde(rename = "draft")]
        Draft,
        #[serde(rename = "paid")]
        Paid,
        #[serde(rename = "cancelled")]
        Cancelled,
        #[serde(rename = "refunded")]
        Refunded,
    }
    impl OrderStatus {
        pub const fn as_db_str(self) -> &'static str {
            match self {
                Self::Draft => "draft",
                Self::Paid => "paid",
                Self::Cancelled => "cancelled",
                Self::Refunded => "refunded",
            }
        }
    }
    impl DbEnum for OrderStatus {
        const TYPE: EnumType = ORDER_STATUS;
        fn as_db_str(self) -> &'static str {
            OrderStatus::as_db_str(self)
        }
    }
    impl std::fmt::Display for OrderStatus {
        fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            formatter.write_str(self.as_db_str())
        }
    }
    impl std::str::FromStr for OrderStatus {
        type Err = &'static str;
        fn from_str(value: &str) -> std::result::Result<Self, Self::Err> {
            match value {
                "draft" => Ok(Self::Draft),
                "paid" => Ok(Self::Paid),
                "cancelled" => Ok(Self::Cancelled),
                "refunded" => Ok(Self::Refunded),
                _ => Err("unknown enum variant"),
            }
        }
    }
    pub const USER_STATUS: EnumType =
        EnumType::new(Some("public"), "user_status", &["active", "disabled"]);
    #[derive(Clone, Copy, Debug, PartialEq, Eq, rqb::serde::Serialize, rqb::serde::Deserialize)]
    #[serde(crate = "rqb::serde")]
    pub enum UserStatus {
        #[serde(rename = "active")]
        Active,
        #[serde(rename = "disabled")]
        Disabled,
    }
    impl UserStatus {
        pub const fn as_db_str(self) -> &'static str {
            match self {
                Self::Active => "active",
                Self::Disabled => "disabled",
            }
        }
    }
    impl DbEnum for UserStatus {
        const TYPE: EnumType = USER_STATUS;
        fn as_db_str(self) -> &'static str {
            UserStatus::as_db_str(self)
        }
    }
    impl std::fmt::Display for UserStatus {
        fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            formatter.write_str(self.as_db_str())
        }
    }
    impl std::str::FromStr for UserStatus {
        type Err = &'static str;
        fn from_str(value: &str) -> std::result::Result<Self, Self::Err> {
            match value {
                "active" => Ok(Self::Active),
                "disabled" => Ok(Self::Disabled),
                _ => Err("unknown enum variant"),
            }
        }
    }
}
pub mod types {
    use rqb::prelude::*;
    pub const UINT_256: TypeSpec = TypeSpec::domain(Some("public"), "uint_256")
        .base(TypeFamily::Numeric)
        .value_repr(ValueRepr::DecimalString)
        .select_repr(SelectRepr::Text);
}
pub mod app_users {
    __rqb_relation!(
        table,
        "public",
        "app_users",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                ORGANIZATION_ID,
                Field::mapped("organizationId", "organization_id", FieldType::Uuid),
                organization_id
            ),
            (EMAIL, Field::new("email", FieldType::Text), email),
            (
                STATUS,
                Field::new("status", FieldType::Enum(super::enums::USER_STATUS)),
                status
            ),
            (
                PROFILE,
                Field::new("profile", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                profile
            ),
            (
                TAGS,
                Field::new("tags", FieldType::Array(ElemType::Text)).sortable(false),
                tags
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod events {
    __rqb_relation!(
        table,
        "public",
        "events",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                ORDER_ID,
                Field::mapped("orderId", "order_id", FieldType::Uuid),
                order_id
            ),
            (
                EVENT_TYPE,
                Field::mapped("eventType", "event_type", FieldType::Text),
                event_type
            ),
            (
                PAYLOAD,
                Field::new("payload", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                payload
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod order_items {
    __rqb_relation!(
        table,
        "public",
        "order_items",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                ORDER_ID,
                Field::mapped("orderId", "order_id", FieldType::Uuid),
                order_id
            ),
            (
                PRODUCT_ID,
                Field::mapped("productId", "product_id", FieldType::Uuid),
                product_id
            ),
            (
                QUANTITY,
                Field::new("quantity", FieldType::Integer),
                quantity
            ),
            (
                UNIT_PRICE_CENTS,
                Field::mapped("unitPriceCents", "unit_price_cents", FieldType::BigInt),
                unit_price_cents
            ),
            (
                METADATA,
                Field::new("metadata", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                metadata
            )
        ]
    );
}
pub mod order_search_view {
    __rqb_relation!(
        view,
        "public",
        "order_search_view",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (EMAIL, Field::new("email", FieldType::Text), email),
            (
                ORGANIZATION_ID,
                Field::mapped("organizationId", "organization_id", FieldType::Uuid),
                organization_id
            ),
            (
                STATUS,
                Field::new("status", FieldType::Enum(super::enums::ORDER_STATUS)),
                status
            ),
            (
                STATUS_HISTORY,
                Field::mapped(
                    "statusHistory",
                    "status_history",
                    FieldType::Array(ElemType::Enum(super::enums::ORDER_STATUS))
                )
                .sortable(false),
                status_history
            ),
            (CHANNEL, Field::new("channel", FieldType::Text), channel),
            (
                TAGS,
                Field::new("tags", FieldType::Array(ElemType::Text)).sortable(false),
                tags
            ),
            (
                METADATA,
                Field::new("metadata", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                metadata
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            ),
            (
                ITEMS_COUNT,
                Field::mapped("itemsCount", "items_count", FieldType::BigInt),
                items_count
            ),
            (
                TOTAL_CENTS,
                Field::mapped("totalCents", "total_cents", FieldType::BigInt),
                total_cents
            )
        ]
    );
}
pub mod orders {
    __rqb_relation!(
        table,
        "public",
        "orders",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                USER_ID,
                Field::mapped("userId", "user_id", FieldType::Uuid),
                user_id
            ),
            (
                STATUS,
                Field::new("status", FieldType::Enum(super::enums::ORDER_STATUS)),
                status
            ),
            (
                STATUS_HISTORY,
                Field::mapped(
                    "statusHistory",
                    "status_history",
                    FieldType::Array(ElemType::Enum(super::enums::ORDER_STATUS))
                )
                .sortable(false),
                status_history
            ),
            (CHANNEL, Field::new("channel", FieldType::Text), channel),
            (
                METADATA,
                Field::new("metadata", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                metadata
            ),
            (
                TAGS,
                Field::new("tags", FieldType::Array(ElemType::Text)).sortable(false),
                tags
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod organizations {
    __rqb_relation!(
        table,
        "public",
        "organizations",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (SLUG, Field::new("slug", FieldType::Text), slug),
            (NAME, Field::new("name", FieldType::Text), name),
            (
                SETTINGS,
                Field::new("settings", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                settings
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod pg_type_examples {
    __rqb_relation!(
        table,
        "public",
        "pg_type_examples",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                DISPLAY_NAME,
                Field::mapped("displayName", "display_name", FieldType::Citext),
                display_name
            ),
            (PAYLOAD, Field::new("payload", FieldType::Bytea), payload),
            (
                IP_ADDR,
                Field::mapped("ipAddr", "ip_addr", FieldType::Inet),
                ip_addr
            ),
            (NETWORK, Field::new("network", FieldType::Cidr), network),
            (
                ACTIVE_WINDOW,
                Field::mapped(
                    "activeWindow",
                    "active_window",
                    FieldType::Range(ElemType::Timestamptz)
                ),
                active_window
            ),
            (
                LOCAL_WINDOW,
                Field::mapped(
                    "localWindow",
                    "local_window",
                    FieldType::Range(ElemType::Timestamp)
                ),
                local_window
            ),
            (
                BILLING_DATES,
                Field::mapped(
                    "billingDates",
                    "billing_dates",
                    FieldType::Range(ElemType::Date)
                ),
                billing_dates
            ),
            (
                CREATED_LOCAL,
                Field::mapped("createdLocal", "created_local", FieldType::Timestamp),
                created_local
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod products {
    __rqb_relation!(
        table,
        "public",
        "products",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (SKU, Field::new("sku", FieldType::Text), sku),
            (NAME, Field::new("name", FieldType::Text), name),
            (
                PRICE_CENTS,
                Field::mapped("priceCents", "price_cents", FieldType::BigInt),
                price_cents
            ),
            (
                ATTRIBUTES,
                Field::new("attributes", FieldType::Jsonb)
                    .sortable(false)
                    .json_paths(JsonPathPolicy::Dynamic),
                attributes
            ),
            (
                TAGS,
                Field::new("tags", FieldType::Array(ElemType::Text)).sortable(false),
                tags
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
pub mod withdrawals {
    __rqb_relation!(
        table,
        "public",
        "withdrawals",
        [
            (ID, Field::new("id", FieldType::Uuid), id),
            (
                USER_ID,
                Field::mapped("userId", "user_id", FieldType::Uuid),
                user_id
            ),
            (
                AMOUNT,
                Field::new("amount", FieldType::Custom(&super::types::UINT_256)),
                amount
            ),
            (
                AMOUNT_HISTORY,
                Field::mapped(
                    "amountHistory",
                    "amount_history",
                    FieldType::Array(ElemType::Custom(&super::types::UINT_256))
                )
                .sortable(false),
                amount_history
            ),
            (
                WALLET_ADDRESS,
                Field::mapped("walletAddress", "wallet_address", FieldType::Text),
                wallet_address
            ),
            (
                CREATED_AT,
                Field::mapped("createdAt", "created_at", FieldType::Timestamptz),
                created_at
            )
        ]
    );
}
