use anyhow::{Context, Result, bail};
use heck::ToSnakeCase;
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::quote;

use crate::ident::{sanitize_ident, unique_ident_strings};
use crate::model::{Column, ColumnType, KnownType, Relation, RelationKind};

const GENERATED_PREAMBLE: &str = r#"// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

"#;
const ROOT_RESERVED_MODULES: &[&str] = &["rqb"];

pub(crate) fn render(relations: &[Relation]) -> Result<String> {
    let module_names = unique_ident_strings(
        relations
            .iter()
            .map(|relation| sanitize_ident(&relation.name.to_snake_case())),
        ROOT_RESERVED_MODULES,
    );
    let modules = relations
        .iter()
        .zip(module_names.iter())
        .map(|(relation, module_name)| render_relation(relation, module_name))
        .collect::<Result<Vec<_>>>()?;
    let tokens = quote! {
        #(#modules)*
    };
    let syntax = syn::parse2(tokens).context("generated schema code did not parse")?;
    let code = format!("{GENERATED_PREAMBLE}{}", prettyplease::unparse(&syntax));
    syn::parse_file(&code).context("generated schema code did not parse")?;
    Ok(code)
}

fn render_relation(relation: &Relation, module_name: &str) -> Result<TokenStream> {
    ensure_unique_api_names(relation)?;

    let module = Ident::new(module_name, Span::call_site());
    let qualified_name = format!("{}.{}", relation.schema, relation.name);
    let source_fn = match relation.kind {
        RelationKind::Table => quote! { rqb::table(#qualified_name, &FIELDS) },
        RelationKind::View => quote! { rqb::view(#qualified_name, &FIELDS) },
    };
    let relation_fn = match relation.kind {
        RelationKind::Table => quote! {
            pub fn table() -> Source {
                #source_fn
            }
        },
        RelationKind::View => quote! {
            pub fn view() -> Source {
                #source_fn
            }
        },
    };

    let metas = relation.columns.iter().map(render_meta);
    let fields = relation.columns.iter().filter_map(render_field);
    let type_imports = render_type_imports(relation);
    let meta_idents = relation
        .columns
        .iter()
        .map(|column| Ident::new(&column.meta_name, Span::call_site()));
    let field_count = Literal::usize_unsuffixed(relation.columns.len());

    Ok(quote! {
        pub mod #module {
            #(#type_imports)*
            use rqb::prelude::*;

            #(#metas)*
            #(#fields)*

            pub static FIELDS: [&Meta; #field_count] = [#(&#meta_idents),*];

            #relation_fn
        }
    })
}

fn render_meta(column: &Column) -> TokenStream {
    let meta = Ident::new(&column.meta_name, Span::call_site());
    let api = &column.api_name;
    let db = &column.name;
    let pg = column.pg_name();
    let ops = ops_tokens(&column.ty);
    let json = json_kind_tokens(&column.ty);
    let base = if api == db {
        quote! { Meta::col(#db, #pg) }
    } else {
        quote! { Meta::new(#api, #db, #pg) }
    };
    let mut expr = quote! { #base.ops(#ops) };
    if let Some(json) = json {
        expr = quote! { #expr.json(#json) };
    }
    quote! {
        pub static #meta: Meta = #expr;
    }
}

fn render_field(column: &Column) -> Option<TokenStream> {
    let ColumnType::Known(known) = &column.ty else {
        return None;
    };
    let const_name = Ident::new(&column.const_name, Span::call_site());
    let meta = Ident::new(&column.meta_name, Span::call_site());
    let rust_ty = rust_type_tokens(known);
    Some(quote! {
        pub const #const_name: Field<#rust_ty> = Field::new(&#meta);
    })
}

fn ensure_unique_api_names(relation: &Relation) -> Result<()> {
    let mut seen = std::collections::BTreeMap::<&str, &str>::new();
    for column in &relation.columns {
        if let Some(first_column) = seen.insert(&column.api_name, &column.name) {
            bail!(
                "columns `{}` and `{}` in relation `{}` both map to API field `{}`",
                first_column,
                column.name,
                relation.name,
                column.api_name
            );
        }
    }
    Ok(())
}

impl Column {
    fn pg_name(&self) -> String {
        match &self.ty {
            ColumnType::Known(known) => pg_name(known),
            ColumnType::RawOnly { pg } => pg.clone(),
        }
    }
}

fn rust_type_tokens(known: &KnownType) -> TokenStream {
    match known {
        KnownType::Text | KnownType::Inet | KnownType::Cidr => quote! { String },
        KnownType::Bool => quote! { bool },
        KnownType::Int2 => quote! { i16 },
        KnownType::Int4 => quote! { i32 },
        KnownType::Int8 => quote! { i64 },
        KnownType::Float4 => quote! { f32 },
        KnownType::Float8 => quote! { f64 },
        KnownType::Numeric => quote! { BigDecimal },
        KnownType::Uuid => quote! { Uuid },
        KnownType::Date => quote! { NaiveDate },
        KnownType::Time => quote! { NaiveTime },
        KnownType::Timetz => {
            quote! { PgTimeTz<NaiveTime, FixedOffset> }
        }
        KnownType::Timestamp => quote! { NaiveDateTime },
        KnownType::Timestamptz => quote! { DateTime<Utc> },
        KnownType::Interval => quote! { PgInterval },
        KnownType::Json => quote! { Value },
        KnownType::Bytes => quote! { Vec<u8> },
        KnownType::Range(elem) => {
            let elem = rust_type_tokens(elem);
            quote! { PgRange<#elem> }
        }
        KnownType::Array(elem) => {
            let elem = rust_type_tokens(elem);
            quote! { Vec<#elem> }
        }
    }
}

#[derive(Default)]
struct TypeImports {
    big_decimal: bool,
    date_time: bool,
    fixed_offset: bool,
    naive_date: bool,
    naive_date_time: bool,
    naive_time: bool,
    pg_interval: bool,
    pg_range: bool,
    pg_time_tz: bool,
    serde_value: bool,
    utc: bool,
    uuid: bool,
}

fn render_type_imports(relation: &Relation) -> Vec<TokenStream> {
    let mut imports = TypeImports::default();
    for column in &relation.columns {
        if let ColumnType::Known(known) = &column.ty {
            collect_type_imports(known, &mut imports);
        }
    }

    let mut rendered = Vec::new();
    let chrono_imports = chrono_imports(&imports);
    if !chrono_imports.is_empty() {
        rendered.push(quote! { use chrono::{#(#chrono_imports),*}; });
    }
    if imports.serde_value {
        rendered.push(quote! { use serde_json::Value; });
    }
    let pg_imports = pg_imports(&imports);
    if !pg_imports.is_empty() {
        rendered.push(quote! { use sqlx::postgres::types::{#(#pg_imports),*}; });
    }
    if imports.big_decimal {
        rendered.push(quote! { use sqlx::types::BigDecimal; });
    }
    if imports.uuid {
        rendered.push(quote! { use uuid::Uuid; });
    }
    rendered
}

fn collect_type_imports(known: &KnownType, imports: &mut TypeImports) {
    match known {
        KnownType::Text
        | KnownType::Bool
        | KnownType::Int2
        | KnownType::Int4
        | KnownType::Int8
        | KnownType::Float4
        | KnownType::Float8
        | KnownType::Bytes
        | KnownType::Inet
        | KnownType::Cidr => {}
        KnownType::Numeric => imports.big_decimal = true,
        KnownType::Uuid => imports.uuid = true,
        KnownType::Date => imports.naive_date = true,
        KnownType::Time => imports.naive_time = true,
        KnownType::Timetz => {
            imports.pg_time_tz = true;
            imports.naive_time = true;
            imports.fixed_offset = true;
        }
        KnownType::Timestamp => imports.naive_date_time = true,
        KnownType::Timestamptz => {
            imports.date_time = true;
            imports.utc = true;
        }
        KnownType::Interval => imports.pg_interval = true,
        KnownType::Json => imports.serde_value = true,
        KnownType::Range(elem) => {
            imports.pg_range = true;
            collect_type_imports(elem, imports);
        }
        KnownType::Array(elem) => collect_type_imports(elem, imports),
    }
}

fn chrono_imports(imports: &TypeImports) -> Vec<Ident> {
    let mut idents = Vec::new();
    push_import(&mut idents, imports.date_time, "DateTime");
    push_import(&mut idents, imports.fixed_offset, "FixedOffset");
    push_import(&mut idents, imports.naive_date, "NaiveDate");
    push_import(&mut idents, imports.naive_date_time, "NaiveDateTime");
    push_import(&mut idents, imports.naive_time, "NaiveTime");
    push_import(&mut idents, imports.utc, "Utc");
    idents
}

fn pg_imports(imports: &TypeImports) -> Vec<Ident> {
    let mut idents = Vec::new();
    push_import(&mut idents, imports.pg_interval, "PgInterval");
    push_import(&mut idents, imports.pg_range, "PgRange");
    push_import(&mut idents, imports.pg_time_tz, "PgTimeTz");
    idents
}

fn push_import(idents: &mut Vec<Ident>, enabled: bool, name: &str) {
    if enabled {
        idents.push(Ident::new(name, Span::call_site()));
    }
}

fn pg_name(known: &KnownType) -> String {
    match known {
        KnownType::Text => "text".to_owned(),
        KnownType::Bool => "bool".to_owned(),
        KnownType::Int2 => "int2".to_owned(),
        KnownType::Int4 => "int4".to_owned(),
        KnownType::Int8 => "int8".to_owned(),
        KnownType::Float4 => "float4".to_owned(),
        KnownType::Float8 => "float8".to_owned(),
        KnownType::Numeric => "numeric".to_owned(),
        KnownType::Uuid => "uuid".to_owned(),
        KnownType::Date => "date".to_owned(),
        KnownType::Time => "time".to_owned(),
        KnownType::Timetz => "timetz".to_owned(),
        KnownType::Timestamp => "timestamp".to_owned(),
        KnownType::Timestamptz => "timestamptz".to_owned(),
        KnownType::Interval => "interval".to_owned(),
        KnownType::Json => "jsonb".to_owned(),
        KnownType::Bytes => "bytea".to_owned(),
        KnownType::Inet => "inet".to_owned(),
        KnownType::Cidr => "cidr".to_owned(),
        KnownType::Range(elem) => match elem.as_ref() {
            KnownType::Int4 => "int4range".to_owned(),
            KnownType::Int8 => "int8range".to_owned(),
            KnownType::Numeric => "numrange".to_owned(),
            KnownType::Date => "daterange".to_owned(),
            KnownType::Timestamp => "tsrange".to_owned(),
            KnownType::Timestamptz => "tstzrange".to_owned(),
            _ => "range".to_owned(),
        },
        KnownType::Array(elem) => format!("{}[]", pg_name(elem)),
    }
}

fn ops_tokens(ty: &ColumnType) -> TokenStream {
    match ty {
        ColumnType::RawOnly { .. } => quote! { OpSet::none() },
        ColumnType::Known(KnownType::Json | KnownType::Bytes | KnownType::Array(_)) => {
            quote! { OpSet::equality() }
        }
        ColumnType::Known(KnownType::Bool | KnownType::Range(_)) => quote! { OpSet::equality() },
        ColumnType::Known(_) => quote! { OpSet::ordered() },
    }
}

fn json_kind_tokens(ty: &ColumnType) -> Option<TokenStream> {
    let kind = match ty {
        ColumnType::Known(KnownType::Text | KnownType::Inet | KnownType::Cidr) => {
            quote! { JsonKind::Text }
        }
        ColumnType::Known(KnownType::Bool) => quote! { JsonKind::Bool },
        ColumnType::Known(KnownType::Int2 | KnownType::Int4) => quote! { JsonKind::Integer },
        ColumnType::Known(KnownType::Int8) => quote! { JsonKind::BigInt },
        ColumnType::Known(KnownType::Float4 | KnownType::Float8) => quote! { JsonKind::Float },
        ColumnType::Known(KnownType::Numeric) => quote! { JsonKind::NumericString },
        ColumnType::Known(KnownType::Uuid) => quote! { JsonKind::Uuid },
        ColumnType::Known(KnownType::Date) => quote! { JsonKind::Date },
        ColumnType::Known(KnownType::Time | KnownType::Timetz) => quote! { JsonKind::Time },
        ColumnType::Known(KnownType::Timestamp) => quote! { JsonKind::Timestamp },
        ColumnType::Known(KnownType::Timestamptz) => quote! { JsonKind::Timestamptz },
        ColumnType::Known(KnownType::Json) => quote! { JsonKind::Jsonb },
        ColumnType::Known(KnownType::Interval | KnownType::Bytes | KnownType::Range(_))
        | ColumnType::Known(KnownType::Array(_))
        | ColumnType::RawOnly { .. } => return None,
    };
    Some(kind)
}

#[cfg(test)]
mod tests {
    use crate::model::{Column, ColumnType, KnownType, Relation, RelationKind};

    use super::render;

    #[test]
    fn renders_sqlx_first_schema_module() {
        let code = render(&[Relation {
            schema: "public".to_owned(),
            name: "app_users".to_owned(),
            kind: RelationKind::Table,
            columns: vec![
                Column {
                    name: "id".to_owned(),
                    api_name: "id".to_owned(),
                    rust_name: "id".to_owned(),
                    const_name: "ID".to_owned(),
                    meta_name: "ID_META".to_owned(),
                    ty: ColumnType::Known(KnownType::Uuid),
                },
                Column {
                    name: "embedding".to_owned(),
                    api_name: "embedding".to_owned(),
                    rust_name: "embedding".to_owned(),
                    const_name: "EMBEDDING".to_owned(),
                    meta_name: "EMBEDDING_META".to_owned(),
                    ty: ColumnType::RawOnly {
                        pg: "vector".to_owned(),
                    },
                },
            ],
        }])
        .unwrap();

        assert!(code.contains("pub static ID_META: Meta"));
        assert!(code.contains("use uuid::Uuid;"));
        assert!(code.contains("pub const ID: Field<Uuid>"));
        assert!(code.contains("pub static EMBEDDING_META: Meta"));
        assert!(!code.contains("pub const EMBEDDING"));
        assert!(code.contains("pub static FIELDS"));
        assert!(code.contains("&ID_META"));
        assert!(code.contains("&EMBEDDING_META"));
        assert!(code.contains("Meta::col(\"id\", \"uuid\")"));
        assert!(code.contains("rqb::table(\"public.app_users\", &FIELDS)"));
        assert!(!code.contains("pub fn source()"));
        assert!(!code.contains("pub fn id()"));
    }
}
