use anyhow::{Context, Result, bail};
use heck::ToSnakeCase;
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;

use crate::ident::{sanitize_ident, unique_ident_strings};
use crate::model::{Column, ColumnType, KnownType, Relation, RelationKind};

const GENERATED_PREAMBLE: &str = r#"// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

"#;
const ROOT_RESERVED_MODULES: &[&str] = &["rqb"];

pub(crate) fn render(relations: &[Relation]) -> Result<String> {
    let module_names = unique_ident_strings(
        relations
            .iter()
            .map(|relation| sanitize_ident(&relation.name.to_snake_case())),
        ROOT_RESERVED_MODULES,
    );
    let modules = relations
        .iter()
        .zip(module_names.iter())
        .map(|(relation, module_name)| render_relation(relation, module_name))
        .collect::<Result<Vec<_>>>()?;
    let tokens = quote! {
        #(#modules)*
    };
    let syntax = syn::parse2(tokens).context("generated schema code did not parse")?;
    let code = format!("{GENERATED_PREAMBLE}{}", prettyplease::unparse(&syntax));
    syn::parse_file(&code).context("generated schema code did not parse")?;
    Ok(code)
}

fn render_relation(relation: &Relation, module_name: &str) -> Result<TokenStream> {
    ensure_unique_api_names(relation)?;

    let module = Ident::new(module_name, Span::call_site());
    let qualified_name = format!("{}.{}", relation.schema, relation.name);
    let source_fn = match relation.kind {
        RelationKind::Table => quote! { rqb::table(#qualified_name, &FIELDS) },
        RelationKind::View => quote! { rqb::view(#qualified_name, &FIELDS) },
    };
    let relation_fn = match relation.kind {
        RelationKind::Table => quote! {
            pub fn table() -> Source {
                source()
            }
        },
        RelationKind::View => quote! {
            pub fn view() -> Source {
                source()
            }
        },
    };

    let metas = relation.columns.iter().map(render_meta);
    let fields = relation.columns.iter().filter_map(render_field);
    let accessors = relation.columns.iter().filter_map(render_accessor);
    let meta_idents = relation
        .columns
        .iter()
        .map(|column| Ident::new(&column.meta_name, Span::call_site()));
    let field_count = relation.columns.len();

    Ok(quote! {
        pub mod #module {
            use rqb::prelude::*;

            #(#metas)*
            #(#fields)*

            pub static FIELDS: [&Meta; #field_count] = [#(&#meta_idents),*];

            pub fn source() -> Source {
                #source_fn
            }

            #relation_fn

            #(#accessors)*
        }
    })
}

fn render_meta(column: &Column) -> TokenStream {
    let meta = Ident::new(&column.meta_name, Span::call_site());
    let api = &column.api_name;
    let db = &column.name;
    let pg = column.pg_name();
    let ops = ops_tokens(&column.ty);
    let json = json_kind_tokens(&column.ty);
    let mut expr = quote! { Meta::new(#api, #db, #pg).ops(#ops) };
    if let Some(json) = json {
        expr = quote! { #expr.json(#json) };
    }
    quote! {
        pub static #meta: Meta = #expr;
    }
}

fn render_field(column: &Column) -> Option<TokenStream> {
    let ColumnType::Known(known) = &column.ty else {
        return None;
    };
    let const_name = Ident::new(&column.const_name, Span::call_site());
    let meta = Ident::new(&column.meta_name, Span::call_site());
    let rust_ty = rust_type_tokens(known);
    Some(quote! {
        pub const #const_name: Field<#rust_ty> = Field::new(&#meta);
    })
}

fn render_accessor(column: &Column) -> Option<TokenStream> {
    let ColumnType::Known(known) = &column.ty else {
        return None;
    };
    let const_name = Ident::new(&column.const_name, Span::call_site());
    let method = Ident::new(&column.rust_name, Span::call_site());
    let rust_ty = rust_type_tokens(known);
    Some(quote! {
        pub fn #method() -> Field<#rust_ty> {
            #const_name
        }
    })
}

fn ensure_unique_api_names(relation: &Relation) -> Result<()> {
    let mut seen = std::collections::BTreeMap::<&str, &str>::new();
    for column in &relation.columns {
        if let Some(first_column) = seen.insert(&column.api_name, &column.name) {
            bail!(
                "columns `{}` and `{}` in relation `{}` both map to API field `{}`",
                first_column,
                column.name,
                relation.name,
                column.api_name
            );
        }
    }
    Ok(())
}

impl Column {
    fn pg_name(&self) -> String {
        match &self.ty {
            ColumnType::Known(known) => pg_name(known),
            ColumnType::RawOnly { pg } => pg.clone(),
        }
    }
}

fn rust_type_tokens(known: &KnownType) -> TokenStream {
    match known {
        KnownType::Text | KnownType::Inet | KnownType::Cidr => quote! { String },
        KnownType::Bool => quote! { bool },
        KnownType::Int2 => quote! { i16 },
        KnownType::Int4 => quote! { i32 },
        KnownType::Int8 => quote! { i64 },
        KnownType::Float4 => quote! { f32 },
        KnownType::Float8 => quote! { f64 },
        KnownType::Numeric => quote! { rqb::sqlx::types::BigDecimal },
        KnownType::Uuid => quote! { rqb::uuid::Uuid },
        KnownType::Date => quote! { rqb::chrono::NaiveDate },
        KnownType::Time => quote! { rqb::chrono::NaiveTime },
        KnownType::Timetz => {
            quote! { rqb::sqlx::postgres::types::PgTimeTz<rqb::chrono::NaiveTime, rqb::chrono::FixedOffset> }
        }
        KnownType::Timestamp => quote! { rqb::chrono::NaiveDateTime },
        KnownType::Timestamptz => quote! { rqb::chrono::DateTime<rqb::chrono::Utc> },
        KnownType::Interval => quote! { rqb::sqlx::postgres::types::PgInterval },
        KnownType::Json => quote! { rqb::serde_json::Value },
        KnownType::Bytes => quote! { Vec<u8> },
        KnownType::Range(elem) => {
            let elem = rust_type_tokens(elem);
            quote! { rqb::sqlx::postgres::types::PgRange<#elem> }
        }
        KnownType::Array(elem) => {
            let elem = rust_type_tokens(elem);
            quote! { Vec<#elem> }
        }
    }
}

fn pg_name(known: &KnownType) -> String {
    match known {
        KnownType::Text => "text".to_owned(),
        KnownType::Bool => "bool".to_owned(),
        KnownType::Int2 => "int2".to_owned(),
        KnownType::Int4 => "int4".to_owned(),
        KnownType::Int8 => "int8".to_owned(),
        KnownType::Float4 => "float4".to_owned(),
        KnownType::Float8 => "float8".to_owned(),
        KnownType::Numeric => "numeric".to_owned(),
        KnownType::Uuid => "uuid".to_owned(),
        KnownType::Date => "date".to_owned(),
        KnownType::Time => "time".to_owned(),
        KnownType::Timetz => "timetz".to_owned(),
        KnownType::Timestamp => "timestamp".to_owned(),
        KnownType::Timestamptz => "timestamptz".to_owned(),
        KnownType::Interval => "interval".to_owned(),
        KnownType::Json => "jsonb".to_owned(),
        KnownType::Bytes => "bytea".to_owned(),
        KnownType::Inet => "inet".to_owned(),
        KnownType::Cidr => "cidr".to_owned(),
        KnownType::Range(elem) => match elem.as_ref() {
            KnownType::Int4 => "int4range".to_owned(),
            KnownType::Int8 => "int8range".to_owned(),
            KnownType::Numeric => "numrange".to_owned(),
            KnownType::Date => "daterange".to_owned(),
            KnownType::Timestamp => "tsrange".to_owned(),
            KnownType::Timestamptz => "tstzrange".to_owned(),
            _ => "range".to_owned(),
        },
        KnownType::Array(elem) => format!("{}[]", pg_name(elem)),
    }
}

fn ops_tokens(ty: &ColumnType) -> TokenStream {
    match ty {
        ColumnType::RawOnly { .. } => quote! { OpSet::none() },
        ColumnType::Known(KnownType::Json | KnownType::Bytes | KnownType::Array(_)) => {
            quote! { OpSet::equality() }
        }
        ColumnType::Known(KnownType::Bool | KnownType::Range(_)) => quote! { OpSet::equality() },
        ColumnType::Known(_) => quote! { OpSet::ordered() },
    }
}

fn json_kind_tokens(ty: &ColumnType) -> Option<TokenStream> {
    let kind = match ty {
        ColumnType::Known(KnownType::Text | KnownType::Inet | KnownType::Cidr) => {
            quote! { JsonKind::Text }
        }
        ColumnType::Known(KnownType::Bool) => quote! { JsonKind::Bool },
        ColumnType::Known(KnownType::Int2 | KnownType::Int4) => quote! { JsonKind::Integer },
        ColumnType::Known(KnownType::Int8) => quote! { JsonKind::BigInt },
        ColumnType::Known(KnownType::Float4 | KnownType::Float8) => quote! { JsonKind::Float },
        ColumnType::Known(KnownType::Numeric) => quote! { JsonKind::NumericString },
        ColumnType::Known(KnownType::Uuid) => quote! { JsonKind::Uuid },
        ColumnType::Known(KnownType::Date) => quote! { JsonKind::Date },
        ColumnType::Known(KnownType::Time | KnownType::Timetz) => quote! { JsonKind::Time },
        ColumnType::Known(KnownType::Timestamp) => quote! { JsonKind::Timestamp },
        ColumnType::Known(KnownType::Timestamptz) => quote! { JsonKind::Timestamptz },
        ColumnType::Known(KnownType::Json) => quote! { JsonKind::Jsonb },
        ColumnType::Known(KnownType::Interval | KnownType::Bytes | KnownType::Range(_))
        | ColumnType::Known(KnownType::Array(_))
        | ColumnType::RawOnly { .. } => return None,
    };
    Some(kind)
}

#[cfg(test)]
mod tests {
    use crate::model::{Column, ColumnType, KnownType, Relation, RelationKind};

    use super::render;

    #[test]
    fn renders_sqlx_first_schema_module() {
        let code = render(&[Relation {
            schema: "public".to_owned(),
            name: "app_users".to_owned(),
            kind: RelationKind::Table,
            columns: vec![
                Column {
                    name: "id".to_owned(),
                    api_name: "id".to_owned(),
                    rust_name: "id".to_owned(),
                    const_name: "ID".to_owned(),
                    meta_name: "ID_META".to_owned(),
                    ty: ColumnType::Known(KnownType::Uuid),
                },
                Column {
                    name: "embedding".to_owned(),
                    api_name: "embedding".to_owned(),
                    rust_name: "embedding".to_owned(),
                    const_name: "EMBEDDING".to_owned(),
                    meta_name: "EMBEDDING_META".to_owned(),
                    ty: ColumnType::RawOnly {
                        pg: "vector".to_owned(),
                    },
                },
            ],
        }])
        .unwrap();

        assert!(code.contains("pub static ID_META: Meta"));
        assert!(code.contains("pub const ID: Field<rqb::uuid::Uuid>"));
        assert!(code.contains("pub static EMBEDDING_META: Meta"));
        assert!(!code.contains("pub const EMBEDDING"));
        assert!(code.contains("pub static FIELDS"));
        assert!(code.contains("&ID_META"));
        assert!(code.contains("&EMBEDDING_META"));
        assert!(code.contains("rqb::table(\"public.app_users\", &FIELDS)"));
    }
}
