use std::collections::BTreeMap;

use anyhow::{Context, Result, bail};
use heck::ToSnakeCase;
use proc_macro2::{Ident, Span};
use quote::quote;
use rqb_core::{ElemType, FieldType, SelectRepr, TypeFamily, ValueRepr};

use crate::ident::{sanitize_ident, unique_enum_variant_idents, unique_ident_strings};
use crate::model::{Column, ColumnType, PgDomain, PgEnum, Relation, RelationKind, SchemaTypeKey};

const GENERATED_PREAMBLE: &str = r#"// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]
#![allow(clippy::module_inception)]

"#;
const RELATION_WRAPPER_MACRO: &str = r#"macro_rules! __rqb_relation_wrapper {
    () => {
        #[derive(Clone, Debug)]
        pub struct Relation {
            inner: rqb::prelude::Relation,
        }

        impl Relation {
            fn new(dataset: Dataset) -> Self {
                Self {
                    inner: rqb::prelude::Relation::new(dataset),
                }
            }

            pub fn alias(mut self, alias: impl Into<String>) -> Self {
                self.inner = self.inner.alias(alias);
                self
            }

            pub fn dataset(&self) -> Dataset {
                self.inner.dataset().clone()
            }
        }

        impl From<Relation> for Dataset {
            fn from(value: Relation) -> Self {
                value.inner.into()
            }
        }

        impl From<&Relation> for Dataset {
            fn from(value: &Relation) -> Self {
                value.dataset()
            }
        }
    };
}

"#;
const RELATION_MACRO: &str = r#"macro_rules! __rqb_relation {
    (
        table,
        $schema:literal,
        $source:literal,
        [$(($const_name:ident, $field_expr:expr, $method_name:ident)),* $(,)?]
    ) => {
        use rqb::prelude::*;

        $(pub const $const_name: Field = $field_expr;)*

        pub const FIELDS: &[Field] = &[$($const_name),*];

        pub fn dataset() -> Dataset {
            Dataset::new_static($source, rqb::Source::static_table($source).schema($schema))
                .static_fields(FIELDS)
        }

        pub fn table() -> Relation {
            Relation::new(dataset())
        }

        __rqb_relation_wrapper!();

        impl Relation {
            $(
                pub fn $method_name(&self) -> FieldRef {
                    self.inner.field($const_name)
                }
            )*
        }
    };
    (
        view,
        $schema:literal,
        $source:literal,
        [$(($const_name:ident, $field_expr:expr, $method_name:ident)),* $(,)?]
    ) => {
        use rqb::prelude::*;

        $(pub const $const_name: Field = $field_expr;)*

        pub const FIELDS: &[Field] = &[$($const_name),*];

        pub fn dataset() -> Dataset {
            Dataset::new_static($source, rqb::Source::static_view($source).schema($schema))
                .static_fields(FIELDS)
        }

        pub fn view() -> Relation {
            Relation::new(dataset())
        }

        __rqb_relation_wrapper!();

        impl Relation {
            $(
                pub fn $method_name(&self) -> FieldRef {
                    self.inner.field($const_name)
                }
            )*
        }
    };
}

"#;
const ROOT_RESERVED_MODULES: &[&str] = &["enums", "types"];
const RELATION_RESERVED_CONSTS: &[&str] = &["FIELDS"];
const RELATION_RESERVED_METHODS: &[&str] = &["new", "alias", "dataset"];

pub(crate) fn render(
    relations: &[Relation],
    enums: &BTreeMap<SchemaTypeKey, PgEnum>,
    domains: &BTreeMap<SchemaTypeKey, PgDomain>,
) -> Result<String> {
    let enum_module = render_enum_module(enums);
    let type_module = render_type_module(domains);
    let module_names = unique_ident_strings(
        relations
            .iter()
            .map(|relation| sanitize_ident(&relation.name.to_snake_case())),
        ROOT_RESERVED_MODULES,
    );
    let modules = relations
        .iter()
        .zip(module_names.iter())
        .map(|(relation, module_name)| render_relation(relation, module_name))
        .collect::<Result<Vec<_>>>()?;
    let tokens = quote! {
        #enum_module
        #type_module
        #(#modules)*
    };
    let syntax = syn::parse2(tokens).context("generated schema code did not parse")?;
    let code = format!(
        "{GENERATED_PREAMBLE}{RELATION_WRAPPER_MACRO}{RELATION_MACRO}{}",
        prettyplease::unparse(&syntax)
    );
    syn::parse_file(&code).context("generated schema code did not parse")?;
    Ok(code)
}

fn render_relation(relation: &Relation, module_name: &str) -> Result<proc_macro2::TokenStream> {
    ensure_unique_api_names(relation)?;

    let module = Ident::new(module_name, Span::call_site());
    let db_schema = &relation.schema;
    let db_name = &relation.name;
    let kind = match relation.kind {
        RelationKind::Table => Ident::new("table", Span::call_site()),
        RelationKind::View => Ident::new("view", Span::call_site()),
    };
    let const_names = unique_ident_strings(
        relation
            .columns
            .iter()
            .map(|column| column.const_name.clone()),
        RELATION_RESERVED_CONSTS,
    );
    let method_names = unique_ident_strings(
        relation
            .columns
            .iter()
            .map(|column| column.rust_name.clone()),
        RELATION_RESERVED_METHODS,
    );
    let fields = relation
        .columns
        .iter()
        .zip(const_names.iter())
        .zip(method_names.iter())
        .map(|((column, const_name), method_name)| {
            let const_name = Ident::new(const_name, Span::call_site());
            let method_name = Ident::new(method_name, Span::call_site());
            let field = field_expr_tokens(column);
            quote! { (#const_name, #field, #method_name) }
        });

    Ok(quote! {
        pub mod #module {
            __rqb_relation!(#kind, #db_schema, #db_name, [#(#fields),*]);
        }
    })
}

fn render_enum_module(enums: &BTreeMap<SchemaTypeKey, PgEnum>) -> proc_macro2::TokenStream {
    let enum_defs = enums.values().map(render_enum_def);
    quote! {
        pub mod enums {
            use rqb::prelude::*;

            #(#enum_defs)*
        }
    }
}

fn render_type_module(domains: &BTreeMap<SchemaTypeKey, PgDomain>) -> proc_macro2::TokenStream {
    let domain_defs = domains.values().map(render_domain_def);
    quote! {
        pub mod types {
            use rqb::prelude::*;

            #(#domain_defs)*
        }
    }
}

fn render_domain_def(domain: &PgDomain) -> proc_macro2::TokenStream {
    let const_name = Ident::new(&domain.const_name, Span::call_site());
    let schema = &domain.schema;
    let name = &domain.name;
    let family = type_family_tokens(domain.family);
    let value_repr = value_repr_tokens(domain.value_repr);
    let select_repr = select_repr_tokens(domain.select_repr);

    quote! {
        pub const #const_name: TypeSpec = TypeSpec::domain(Some(#schema), #name)
            .base(#family)
            .value_repr(#value_repr)
            .select_repr(#select_repr);
    }
}

fn render_enum_def(pg_enum: &PgEnum) -> proc_macro2::TokenStream {
    let const_name = Ident::new(&pg_enum.const_name, Span::call_site());
    let rust_name = Ident::new(&pg_enum.rust_name, Span::call_site());
    let schema = &pg_enum.schema;
    let name = &pg_enum.name;
    let variants = &pg_enum.variants;
    let variant_idents = unique_enum_variant_idents(&pg_enum.variants);

    let variant_defs = variants
        .iter()
        .zip(variant_idents.iter())
        .map(|(variant, ident)| {
            quote! {
                #[serde(rename = #variant)]
                #ident
            }
        });

    quote! {
        pub const #const_name: EnumType = EnumType::new(
            Some(#schema),
            #name,
            &[#(#variants),*],
        );

        #[derive(Clone, Copy, Debug, PartialEq, Eq, rqb::serde::Serialize, rqb::serde::Deserialize)]
        #[serde(crate = "rqb::serde")]
        pub enum #rust_name {
            #(#variant_defs),*
        }

        impl #rust_name {
            pub const fn as_db_str(self) -> &'static str {
                match self {
                    #(Self::#variant_idents => #variants),*
                }
            }
        }

        impl DbEnum for #rust_name {
            const TYPE: EnumType = #const_name;

            fn as_db_str(self) -> &'static str {
                #rust_name::as_db_str(self)
            }
        }

        impl std::fmt::Display for #rust_name {
            fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                formatter.write_str(self.as_db_str())
            }
        }

        impl std::str::FromStr for #rust_name {
            type Err = &'static str;

            fn from_str(value: &str) -> std::result::Result<Self, Self::Err> {
                match value {
                    #(#variants => Ok(Self::#variant_idents),)*
                    _ => Err("unknown enum variant"),
                }
            }
        }
    }
}

fn field_expr_tokens(column: &Column) -> proc_macro2::TokenStream {
    let api_name = &column.api_name;
    let db_name = &column.name;
    let field_type = field_type_tokens(&column.field_type);
    let mut expr = if column.api_name == column.name {
        quote! { Field::new(#api_name, #field_type) }
    } else {
        quote! { Field::mapped(#api_name, #db_name, #field_type) }
    };

    if column.field_type.is_jsonb() {
        expr = quote! { #expr.sortable(false).json_paths(JsonPathPolicy::Dynamic) };
    }
    if column.field_type.is_array() {
        expr = quote! { #expr.sortable(false) };
    }

    expr
}

fn ensure_unique_api_names(relation: &Relation) -> Result<()> {
    let mut seen = BTreeMap::<&str, &str>::new();
    for column in &relation.columns {
        if let Some(first_column) = seen.insert(&column.api_name, &column.name) {
            bail!(
                "columns `{}` and `{}` in relation `{}` both map to API field `{}`",
                first_column,
                column.name,
                relation.name,
                column.api_name
            );
        }
    }
    Ok(())
}

fn field_type_tokens(field_type: &ColumnType) -> proc_macro2::TokenStream {
    match field_type {
        ColumnType::Core(field_type) => core_field_type_tokens(*field_type),
        ColumnType::Enum(pg_enum) => {
            let const_name = Ident::new(&pg_enum.const_name, Span::call_site());
            quote! { FieldType::Enum(super::enums::#const_name) }
        }
        ColumnType::ArrayEnum(pg_enum) => {
            let const_name = Ident::new(&pg_enum.const_name, Span::call_site());
            quote! { FieldType::Array(ElemType::Enum(super::enums::#const_name)) }
        }
        ColumnType::Domain(domain) => {
            let const_name = Ident::new(&domain.const_name, Span::call_site());
            quote! { FieldType::Custom(&super::types::#const_name) }
        }
        ColumnType::ArrayDomain(domain) => {
            let const_name = Ident::new(&domain.const_name, Span::call_site());
            quote! { FieldType::Array(ElemType::Custom(&super::types::#const_name)) }
        }
    }
}

fn core_field_type_tokens(field_type: FieldType) -> proc_macro2::TokenStream {
    match field_type {
        FieldType::Text => quote! { FieldType::Text },
        FieldType::Citext => quote! { FieldType::Citext },
        FieldType::Integer => quote! { FieldType::Integer },
        FieldType::BigInt => quote! { FieldType::BigInt },
        FieldType::Float => quote! { FieldType::Float },
        FieldType::Numeric => quote! { FieldType::Numeric },
        FieldType::Bool => quote! { FieldType::Bool },
        FieldType::Uuid => quote! { FieldType::Uuid },
        FieldType::Timestamp => quote! { FieldType::Timestamp },
        FieldType::Timestamptz => quote! { FieldType::Timestamptz },
        FieldType::Date => quote! { FieldType::Date },
        FieldType::Time => quote! { FieldType::Time },
        FieldType::Timetz => quote! { FieldType::Timetz },
        FieldType::Interval => quote! { FieldType::Interval },
        FieldType::Jsonb => quote! { FieldType::Jsonb },
        FieldType::Bytea => quote! { FieldType::Bytea },
        FieldType::Inet => quote! { FieldType::Inet },
        FieldType::Cidr => quote! { FieldType::Cidr },
        FieldType::Custom(_) => unreachable!("custom types are rendered from ColumnType::Domain"),
        FieldType::Range(elem_type) => {
            let elem_type = elem_type_tokens(elem_type);
            quote! { FieldType::Range(#elem_type) }
        }
        FieldType::Array(elem_type) => {
            let elem_type = elem_type_tokens(elem_type);
            quote! { FieldType::Array(#elem_type) }
        }
        FieldType::Enum(_) => unreachable!("core enum types are rendered from ColumnType::Enum"),
    }
}

fn elem_type_tokens(elem_type: ElemType) -> proc_macro2::TokenStream {
    match elem_type {
        ElemType::Text => quote! { ElemType::Text },
        ElemType::Citext => quote! { ElemType::Citext },
        ElemType::Int => quote! { ElemType::Int },
        ElemType::BigInt => quote! { ElemType::BigInt },
        ElemType::Float => quote! { ElemType::Float },
        ElemType::Numeric => quote! { ElemType::Numeric },
        ElemType::Bool => quote! { ElemType::Bool },
        ElemType::Uuid => quote! { ElemType::Uuid },
        ElemType::Timestamp => quote! { ElemType::Timestamp },
        ElemType::Timestamptz => quote! { ElemType::Timestamptz },
        ElemType::Date => quote! { ElemType::Date },
        ElemType::Time => quote! { ElemType::Time },
        ElemType::Timetz => quote! { ElemType::Timetz },
        ElemType::Interval => quote! { ElemType::Interval },
        ElemType::Enum(_) => {
            unreachable!("enum element types are rendered from ColumnType::ArrayEnum")
        }
        ElemType::Custom(_) => {
            unreachable!("custom element types are rendered from ColumnType::ArrayDomain")
        }
    }
}

fn type_family_tokens(family: TypeFamily) -> proc_macro2::TokenStream {
    match family {
        TypeFamily::Text => quote! { TypeFamily::Text },
        TypeFamily::Numeric => quote! { TypeFamily::Numeric },
        TypeFamily::Bool => quote! { TypeFamily::Bool },
        TypeFamily::Uuid => quote! { TypeFamily::Uuid },
        TypeFamily::Timestamp => quote! { TypeFamily::Timestamp },
        TypeFamily::Timestamptz => quote! { TypeFamily::Timestamptz },
        TypeFamily::Date => quote! { TypeFamily::Date },
        TypeFamily::Time => quote! { TypeFamily::Time },
        TypeFamily::Timetz => quote! { TypeFamily::Timetz },
        TypeFamily::Interval => quote! { TypeFamily::Interval },
        TypeFamily::Jsonb => quote! { TypeFamily::Jsonb },
        TypeFamily::Bytes => quote! { TypeFamily::Bytes },
        TypeFamily::Network => quote! { TypeFamily::Network },
        TypeFamily::Range => quote! { TypeFamily::Range },
    }
}

fn value_repr_tokens(value_repr: ValueRepr) -> proc_macro2::TokenStream {
    match value_repr {
        ValueRepr::Native => quote! { ValueRepr::Native },
        ValueRepr::String => quote! { ValueRepr::String },
        ValueRepr::DecimalString => quote! { ValueRepr::DecimalString },
    }
}

fn select_repr_tokens(select_repr: SelectRepr) -> proc_macro2::TokenStream {
    match select_repr {
        SelectRepr::Native => quote! { SelectRepr::Native },
        SelectRepr::Text => quote! { SelectRepr::Text },
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use rqb_core::{FieldType, SelectRepr, TypeFamily, ValueRepr};

    use crate::model::{Column, ColumnType, PgDomain, PgEnum, Relation, RelationKind};

    use super::render;

    #[test]
    fn renders_ergonomic_generated_module() {
        let code = render(
            &[Relation {
                schema: "reporting".to_owned(),
                name: "order_search_view".to_owned(),
                kind: RelationKind::View,
                columns: vec![
                    Column {
                        name: "created_at".to_owned(),
                        api_name: "createdAt".to_owned(),
                        rust_name: "created_at".to_owned(),
                        const_name: "CREATED_AT".to_owned(),
                        field_type: ColumnType::Core(FieldType::Timestamp),
                    },
                    Column {
                        name: "metadata".to_owned(),
                        api_name: "metadata".to_owned(),
                        rust_name: "metadata".to_owned(),
                        const_name: "METADATA".to_owned(),
                        field_type: ColumnType::Core(FieldType::Jsonb),
                    },
                ],
            }],
            &BTreeMap::new(),
            &BTreeMap::new(),
        )
        .unwrap();

        assert!(code.starts_with("// @generated by rqb-cli. Do not edit by hand."));
        assert!(code.contains("#![allow(dead_code)]"));
        assert!(code.contains("pub mod order_search_view"));
        assert!(code.contains("macro_rules! __rqb_relation"));
        assert!(code.contains("__rqb_relation!"));
        assert!(code.contains("\"reporting\""));
        assert!(code.contains("\"order_search_view\""));
        assert!(code.contains("(CREATED_AT,"));
        assert!(code.contains("\"createdAt\""));
        assert!(code.contains("\"created_at\""));
        assert!(code.contains("Field::mapped"));
        assert!(code.contains("FieldType::Timestamp"));
        assert!(code.contains(
            "Dataset::new_static($source, rqb::Source::static_view($source).schema($schema))"
        ));
        assert!(code.contains("pub fn view() -> Relation"));
        assert!(!code.contains("pub fn relation()"));
        assert!(code.contains("macro_rules! __rqb_relation_wrapper"));
        assert!(code.contains("__rqb_relation_wrapper!();"));
        assert!(code.contains("self.inner.field($const_name)"));
        assert!(code.contains(".json_paths(JsonPathPolicy::Dynamic)"));
    }

    #[test]
    fn renders_postgres_enum_module_and_fields() {
        let pg_enum = PgEnum {
            schema: "public".to_owned(),
            name: "order_status".to_owned(),
            const_name: "ORDER_STATUS".to_owned(),
            rust_name: "OrderStatus".to_owned(),
            variants: vec!["draft".to_owned(), "paid".to_owned()],
        };
        let mut enums = BTreeMap::new();
        enums.insert(
            (pg_enum.schema.clone(), pg_enum.name.clone()),
            pg_enum.clone(),
        );

        let code = render(
            &[Relation {
                schema: "public".to_owned(),
                name: "orders".to_owned(),
                kind: RelationKind::Table,
                columns: vec![
                    Column {
                        name: "status".to_owned(),
                        api_name: "status".to_owned(),
                        rust_name: "status".to_owned(),
                        const_name: "STATUS".to_owned(),
                        field_type: ColumnType::Enum(pg_enum.clone()),
                    },
                    Column {
                        name: "status_history".to_owned(),
                        api_name: "statusHistory".to_owned(),
                        rust_name: "status_history".to_owned(),
                        const_name: "STATUS_HISTORY".to_owned(),
                        field_type: ColumnType::ArrayEnum(pg_enum),
                    },
                ],
            }],
            &enums,
            &BTreeMap::new(),
        )
        .unwrap();

        assert!(code.contains("pub mod enums"));
        assert!(code.contains("pub const ORDER_STATUS: EnumType"));
        assert!(code.contains("pub enum OrderStatus"));
        assert!(code.contains("rqb::serde::Serialize"));
        assert!(code.contains("rqb::serde::Deserialize"));
        assert!(code.contains("#[serde(crate = \"rqb::serde\")]"));
        assert!(code.contains("#[serde(rename = \"draft\")]"));
        assert!(code.contains("impl DbEnum for OrderStatus"));
        assert!(code.contains("impl std::str::FromStr for OrderStatus"));
        assert!(code.contains("FieldType::Enum(super::enums::ORDER_STATUS)"));
        assert!(code.contains("FieldType::Array(ElemType::Enum(super::enums::ORDER_STATUS))"));
    }

    #[test]
    fn renders_postgres_domain_module_and_fields() {
        let domain = PgDomain {
            schema: "public".to_owned(),
            name: "uint_256".to_owned(),
            const_name: "UINT_256".to_owned(),
            family: TypeFamily::Numeric,
            value_repr: ValueRepr::DecimalString,
            select_repr: SelectRepr::Text,
        };
        let mut domains = BTreeMap::new();
        domains.insert((domain.schema.clone(), domain.name.clone()), domain.clone());

        let code = render(
            &[Relation {
                schema: "public".to_owned(),
                name: "withdrawals".to_owned(),
                kind: RelationKind::Table,
                columns: vec![
                    Column {
                        name: "amount".to_owned(),
                        api_name: "amount".to_owned(),
                        rust_name: "amount".to_owned(),
                        const_name: "AMOUNT".to_owned(),
                        field_type: ColumnType::Domain(domain.clone()),
                    },
                    Column {
                        name: "amount_history".to_owned(),
                        api_name: "amountHistory".to_owned(),
                        rust_name: "amount_history".to_owned(),
                        const_name: "AMOUNT_HISTORY".to_owned(),
                        field_type: ColumnType::ArrayDomain(domain),
                    },
                ],
            }],
            &BTreeMap::new(),
            &domains,
        )
        .unwrap();

        assert!(code.contains("pub mod types"));
        assert!(code.contains("pub const UINT_256: TypeSpec"));
        assert!(code.contains("TypeSpec::domain(Some(\"public\"), \"uint_256\")"));
        assert!(code.contains(".base(TypeFamily::Numeric)"));
        assert!(code.contains(".value_repr(ValueRepr::DecimalString)"));
        assert!(code.contains(".select_repr(SelectRepr::Text)"));
        assert!(code.contains("FieldType::Custom"));
        assert!(code.contains("FieldType::Array"));
        assert!(code.contains("ElemType::Custom"));
        assert!(code.contains("super::types::UINT_256"));
        assert!(code.contains(".sortable(false)"));
    }

    #[test]
    fn disambiguates_generated_rust_identifiers() {
        let code = render(
            &[
                Relation {
                    schema: "public".to_owned(),
                    name: "types".to_owned(),
                    kind: RelationKind::Table,
                    columns: vec![
                        Column {
                            name: "fields".to_owned(),
                            api_name: "fields".to_owned(),
                            rust_name: "dataset".to_owned(),
                            const_name: "FIELDS".to_owned(),
                            field_type: ColumnType::Core(FieldType::Text),
                        },
                        Column {
                            name: "fields_2".to_owned(),
                            api_name: "fields2".to_owned(),
                            rust_name: "dataset".to_owned(),
                            const_name: "FIELDS".to_owned(),
                            field_type: ColumnType::Core(FieldType::Text),
                        },
                    ],
                },
                Relation {
                    schema: "public".to_owned(),
                    name: "types".to_owned(),
                    kind: RelationKind::View,
                    columns: Vec::new(),
                },
            ],
            &BTreeMap::new(),
            &BTreeMap::new(),
        )
        .unwrap();

        assert!(code.contains("pub mod types_1"));
        assert!(code.contains("pub mod types_2"));
        assert!(code.contains("(FIELDS_1,"));
        assert!(code.contains("(FIELDS_2,"));
        assert!(code.contains("dataset_1"));
        assert!(code.contains("dataset_2"));
    }

    #[test]
    fn rejects_api_name_collisions() {
        let error = render(
            &[Relation {
                schema: "public".to_owned(),
                name: "bad_columns".to_owned(),
                kind: RelationKind::Table,
                columns: vec![
                    Column {
                        name: "foo_bar".to_owned(),
                        api_name: "fooBar".to_owned(),
                        rust_name: "foo_bar".to_owned(),
                        const_name: "FOO_BAR".to_owned(),
                        field_type: ColumnType::Core(FieldType::Text),
                    },
                    Column {
                        name: "foo-bar".to_owned(),
                        api_name: "fooBar".to_owned(),
                        rust_name: "foo_bar".to_owned(),
                        const_name: "FOO_BAR".to_owned(),
                        field_type: ColumnType::Core(FieldType::Text),
                    },
                ],
            }],
            &BTreeMap::new(),
            &BTreeMap::new(),
        )
        .unwrap_err();

        assert!(error.to_string().contains("both map to API field `fooBar`"));
    }
}
