[package]
name = "rqb-sample-rest-api"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
async-stream = "0.3"
axum = { version = "0.8", default-features = false, features = ["json", "query", "tokio"] }
chrono = { version = "0.4", features = ["serde"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
rqb = { path = "../../crates/rqb" }
rqb-sample-schema = { path = "../schema" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "uuid", "chrono", "json", "runtime-tokio-rustls", "derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["serde", "v4"] }
