[package]
name = "rqb-sample-rest"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rqb = { path = "../../crates/rqb", features = ["pool", "with-uuid", "with-chrono"] }
actix-web = "4.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.18", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
