[workspace]
members = [
    "crates/rqb",
    "crates/rqb-cli",
    "crates/rqb-macros",
]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mudake-rs/rqb"

[workspace.dependencies]
anyhow = "1.0.103"
async-stream = "0.3.6"
clap = { version = "4.6.1", features = ["derive", "env"] }
heck = "0.5.0"
itoa = "1.0.18"
proc-macro2 = "1.0.106"
quote = "1.0.46"
rqb-macros = { path = "crates/rqb-macros", version = "0.1.3" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
syn = "2.0.118"
thiserror = "2.0.18"
toml = "1.1.2"
sqlx = { version = "0.9.0", default-features = false, features = ["postgres", "json", "uuid", "chrono", "bigdecimal", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.23.4", default-features = false, features = ["serde", "std"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock", "serde", "std"] }
futures-core = "0.3.32"
futures-util = { version = "0.3.32", default-features = false, features = ["std"] }
