[workspace]
members = [
    "crates/rqb",
    "crates/rqb-cli",
    "crates/rqb-macros",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/epolishko/rqb"

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive", "env"] }
heck = "0.5.0"
itoa = "1"
proc-macro2 = "1.0.103"
quote = "1.0.42"
rqb-macros = { path = "crates/rqb-macros", version = "0.1.0" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syn = "2.0.111"
thiserror = "2.0.17"
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "json", "uuid", "chrono", "bigdecimal", "runtime-tokio-rustls"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", default-features = false, features = ["serde", "std"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde", "std"] }
