// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

use chrono::{DateTime, Utc};
use serde_json::Value;
use uuid::Uuid;

rqb::schema! {
    view sample.order_search_view {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        organization_id: uuid = Uuid,
        organization_slug: text = String,
        user_email: text = String,
        status: text = String,
        total_cents: int8 = i64,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        item_count: int8 = i64,
        event_count: int8 = i64,
        last_event_at: timestamptz = DateTime<Utc>,
    }
}
