[package]
name = "rqb-sample-joins-and-aggregates"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rqb = { path = "../../crates/rqb" }
rqb-sample-schema = { path = "../schema" }
serde_json = "1.0.150"
uuid = "1.23.4"

[dev-dependencies]
uuid = { version = "1.23.4", features = ["v4"] }
sqlx = { version = "0.9.0", default-features = false, features = ["postgres", "runtime-tokio", "derive", "bigdecimal"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
