[package]
name = "rqb-sample-schema"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
chrono = "0.4"
rqb = { path = "../../crates/rqb" }
serde_json = "1"
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "bigdecimal", "chrono"] }
uuid = "1"
