// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

use chrono::{DateTime, Utc};
use serde_json::Value;
use uuid::Uuid;

rqb::schema! {
    table sample.app_users {
        id: uuid = Uuid,
        organization_id: uuid = Uuid,
        email: text = String,
        status: text = String,
        display_name: text = String,
        active: bool = bool,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.orders {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        status: text = String,
        total_cents: int8 = i64,
        metadata: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
    }
}
