// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

pub mod app_users {
    use rqb::prelude::*;

    pub static ID_META: Meta = Meta::new("id", "id", "uuid")
        .ops(OpSet::ordered())
        .json(JsonKind::Uuid);
    pub static EMAIL_META: Meta = Meta::new("email", "email", "text")
        .ops(OpSet::ordered())
        .json(JsonKind::Text);
    pub static DISPLAY_NAME_META: Meta = Meta::new("display_name", "display_name", "text")
        .ops(OpSet::ordered())
        .json(JsonKind::Text);
    pub static ACTIVE_META: Meta = Meta::new("active", "active", "bool")
        .ops(OpSet::equality())
        .json(JsonKind::Bool);
    pub static CREATED_AT_META: Meta = Meta::new("created_at", "created_at", "timestamptz")
        .ops(OpSet::ordered())
        .json(JsonKind::Timestamptz);
    pub const ID: Field<rqb::uuid::Uuid> = Field::new(&ID_META);
    pub const EMAIL: Field<String> = Field::new(&EMAIL_META);
    pub const DISPLAY_NAME: Field<String> = Field::new(&DISPLAY_NAME_META);
    pub const ACTIVE: Field<bool> = Field::new(&ACTIVE_META);
    pub const CREATED_AT: Field<rqb::chrono::DateTime<rqb::chrono::Utc>> =
        Field::new(&CREATED_AT_META);
    pub static FIELDS: [&Meta; 5] = [
        &ID_META,
        &EMAIL_META,
        &DISPLAY_NAME_META,
        &ACTIVE_META,
        &CREATED_AT_META,
    ];
    pub fn source() -> Source {
        rqb::table("public.app_users", &FIELDS)
    }
    pub fn table() -> Source {
        source()
    }
    pub fn id() -> Field<rqb::uuid::Uuid> {
        ID
    }
    pub fn email() -> Field<String> {
        EMAIL
    }
    pub fn display_name() -> Field<String> {
        DISPLAY_NAME
    }
    pub fn active() -> Field<bool> {
        ACTIVE
    }
    pub fn created_at() -> Field<rqb::chrono::DateTime<rqb::chrono::Utc>> {
        CREATED_AT
    }
}

pub mod orders {
    use rqb::prelude::*;

    pub static ID_META: Meta = Meta::new("id", "id", "uuid")
        .ops(OpSet::ordered())
        .json(JsonKind::Uuid);
    pub static USER_ID_META: Meta = Meta::new("user_id", "user_id", "uuid")
        .ops(OpSet::ordered())
        .json(JsonKind::Uuid);
    pub static STATUS_META: Meta = Meta::new("status", "status", "text")
        .ops(OpSet::ordered())
        .json(JsonKind::Text);
    pub static TOTAL_CENTS_META: Meta = Meta::new("total_cents", "total_cents", "int8")
        .ops(OpSet::ordered())
        .json(JsonKind::BigInt);
    pub static CREATED_AT_META: Meta = Meta::new("created_at", "created_at", "timestamptz")
        .ops(OpSet::ordered())
        .json(JsonKind::Timestamptz);
    pub const ID: Field<rqb::uuid::Uuid> = Field::new(&ID_META);
    pub const USER_ID: Field<rqb::uuid::Uuid> = Field::new(&USER_ID_META);
    pub const STATUS: Field<String> = Field::new(&STATUS_META);
    pub const TOTAL_CENTS: Field<i64> = Field::new(&TOTAL_CENTS_META);
    pub const CREATED_AT: Field<rqb::chrono::DateTime<rqb::chrono::Utc>> =
        Field::new(&CREATED_AT_META);
    pub static FIELDS: [&Meta; 5] = [
        &ID_META,
        &USER_ID_META,
        &STATUS_META,
        &TOTAL_CENTS_META,
        &CREATED_AT_META,
    ];
    pub fn source() -> Source {
        rqb::table("public.orders", &FIELDS)
    }
    pub fn table() -> Source {
        source()
    }
    pub fn id() -> Field<rqb::uuid::Uuid> {
        ID
    }
    pub fn user_id() -> Field<rqb::uuid::Uuid> {
        USER_ID
    }
    pub fn status() -> Field<String> {
        STATUS
    }
    pub fn total_cents() -> Field<i64> {
        TOTAL_CENTS
    }
    pub fn created_at() -> Field<rqb::chrono::DateTime<rqb::chrono::Utc>> {
        CREATED_AT
    }
}
