[package]
name = "rqb"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "sqlx-first typed Postgres query builder."
readme = "../../README.md"
keywords = ["postgres", "query-builder", "sql", "database", "async"]
categories = ["database", "web-programming"]

[features]
default = []

[dependencies]
chrono.workspace = true
rqb-macros.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }
