// @generated by rqb-cli. Do not edit by hand.

//! Generated rqb schema metadata.
//!
//! Relation modules expose typed fields, relation sources, alias handles, and
//! unique constraint names for use with the `rqb` query builder.

#![allow(dead_code)]

rqb::schema! {
    table sample_custom.wallets {
        id: int4 = i32,
        #[rqb(ops = ordered, json = big_int)]
        balance: "sample_custom.cents" = crate::types::Cents,
        constraints {
            WALLETS_PKEY: "wallets_pkey",
        }
    }
}
