// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

pub mod invoices {
    use chrono::{DateTime, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, Utc};
    use rqb::prelude::*;
    use serde_json::Value;
    use sqlx::postgres::types::{PgInterval, PgRange, PgTimeTz};
    use sqlx::types::BigDecimal;
    use uuid::Uuid;
    pub static ID_META: Meta = Meta::col("id", "uuid")
        .ops(OpSet::ordered())
        .json(JsonKind::Uuid);
    pub static INVOICE_NO_META: Meta = Meta::col("invoice_no", "int8")
        .ops(OpSet::ordered())
        .json(JsonKind::BigInt);
    pub static CUSTOMER_ID_META: Meta = Meta::col("customer_id", "uuid")
        .ops(OpSet::ordered())
        .json(JsonKind::Uuid);
    pub static STATE_META: Meta = Meta::col("state", "invoice_state").ops(OpSet::none());
    pub static AMOUNT_META: Meta = Meta::col("amount", "numeric")
        .ops(OpSet::ordered())
        .json(JsonKind::NumericString);
    pub static TAX_RATE_META: Meta = Meta::col("tax_rate", "numeric")
        .ops(OpSet::ordered())
        .json(JsonKind::NumericString);
    pub static AMOUNT_HISTORY_META: Meta =
        Meta::col("amount_history", "numeric[]").ops(OpSet::equality());
    pub static DUE_ON_META: Meta = Meta::col("due_on", "date")
        .ops(OpSet::ordered())
        .json(JsonKind::Date);
    pub static ISSUED_AT_META: Meta = Meta::col("issued_at", "timestamp")
        .ops(OpSet::ordered())
        .json(JsonKind::Timestamp);
    pub static PAID_AT_META: Meta = Meta::col("paid_at", "timestamptz")
        .ops(OpSet::ordered())
        .json(JsonKind::Timestamptz);
    pub static REMINDER_TIME_META: Meta = Meta::col("reminder_time", "time")
        .ops(OpSet::ordered())
        .json(JsonKind::Time);
    pub static CUTOFF_TIME_META: Meta = Meta::col("cutoff_time", "timetz")
        .ops(OpSet::ordered())
        .json(JsonKind::Time);
    pub static GRACE_PERIOD_META: Meta =
        Meta::col("grace_period", "interval").ops(OpSet::ordered());
    pub static SERVICE_DAYS_META: Meta =
        Meta::col("service_days", "daterange").ops(OpSet::equality());
    pub static BILLING_WINDOW_META: Meta =
        Meta::col("billing_window", "tstzrange").ops(OpSet::equality());
    pub static CLIENT_IP_META: Meta = Meta::col("client_ip", "inet")
        .ops(OpSet::ordered())
        .json(JsonKind::Text);
    pub static CLIENT_NETWORK_META: Meta = Meta::col("client_network", "cidr")
        .ops(OpSet::ordered())
        .json(JsonKind::Text);
    pub static PDF_META: Meta = Meta::col("pdf", "bytea").ops(OpSet::equality());
    pub static TAGS_META: Meta = Meta::col("tags", "text[]").ops(OpSet::equality());
    pub static METADATA_META: Meta = Meta::col("metadata", "jsonb")
        .ops(OpSet::equality())
        .json(JsonKind::Jsonb);
    pub const ID: Field<Uuid> = Field::new(&ID_META);
    pub const INVOICE_NO: Field<i64> = Field::new(&INVOICE_NO_META);
    pub const CUSTOMER_ID: Field<Uuid> = Field::new(&CUSTOMER_ID_META);
    pub const AMOUNT: Field<BigDecimal> = Field::new(&AMOUNT_META);
    pub const TAX_RATE: Field<BigDecimal> = Field::new(&TAX_RATE_META);
    pub const AMOUNT_HISTORY: Field<Vec<BigDecimal>> = Field::new(&AMOUNT_HISTORY_META);
    pub const DUE_ON: Field<NaiveDate> = Field::new(&DUE_ON_META);
    pub const ISSUED_AT: Field<NaiveDateTime> = Field::new(&ISSUED_AT_META);
    pub const PAID_AT: Field<DateTime<Utc>> = Field::new(&PAID_AT_META);
    pub const REMINDER_TIME: Field<NaiveTime> = Field::new(&REMINDER_TIME_META);
    pub const CUTOFF_TIME: Field<PgTimeTz<NaiveTime, FixedOffset>> = Field::new(&CUTOFF_TIME_META);
    pub const GRACE_PERIOD: Field<PgInterval> = Field::new(&GRACE_PERIOD_META);
    pub const SERVICE_DAYS: Field<PgRange<NaiveDate>> = Field::new(&SERVICE_DAYS_META);
    pub const BILLING_WINDOW: Field<PgRange<DateTime<Utc>>> = Field::new(&BILLING_WINDOW_META);
    pub const CLIENT_IP: Field<String> = Field::new(&CLIENT_IP_META);
    pub const CLIENT_NETWORK: Field<String> = Field::new(&CLIENT_NETWORK_META);
    pub const PDF: Field<Vec<u8>> = Field::new(&PDF_META);
    pub const TAGS: Field<Vec<String>> = Field::new(&TAGS_META);
    pub const METADATA: Field<Value> = Field::new(&METADATA_META);
    pub static FIELDS: [&Meta; 20] = [
        &ID_META,
        &INVOICE_NO_META,
        &CUSTOMER_ID_META,
        &STATE_META,
        &AMOUNT_META,
        &TAX_RATE_META,
        &AMOUNT_HISTORY_META,
        &DUE_ON_META,
        &ISSUED_AT_META,
        &PAID_AT_META,
        &REMINDER_TIME_META,
        &CUTOFF_TIME_META,
        &GRACE_PERIOD_META,
        &SERVICE_DAYS_META,
        &BILLING_WINDOW_META,
        &CLIENT_IP_META,
        &CLIENT_NETWORK_META,
        &PDF_META,
        &TAGS_META,
        &METADATA_META,
    ];
    pub fn table() -> Source {
        rqb::table("sample.invoices", &FIELDS)
    }
}
