// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

use chrono::{DateTime, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, Utc};
use serde_json::Value;
use sqlx::postgres::types::{PgInterval, PgRange, PgTimeTz};
use sqlx::types::BigDecimal;
use uuid::Uuid;

rqb::schema! {
    table sample.invoices {
        id: uuid = Uuid,
        invoice_no: int8 = i64,
        customer_id: uuid = Uuid,
        state: invoice_state,
        amount: numeric = BigDecimal,
        tax_rate: numeric = BigDecimal,
        amount_history: "numeric[]" = Vec<BigDecimal>,
        due_on: date = NaiveDate,
        issued_at: timestamp = NaiveDateTime,
        paid_at: timestamptz = DateTime<Utc>,
        reminder_time: time = NaiveTime,
        cutoff_time: timetz = PgTimeTz<NaiveTime, FixedOffset>,
        grace_period: interval = PgInterval,
        service_days: daterange = PgRange<NaiveDate>,
        billing_window: tstzrange = PgRange<DateTime<Utc>>,
        client_ip: inet = String,
        client_network: cidr = String,
        pdf: bytea = Vec<u8>,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
    }
}
