// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

use chrono::{DateTime, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, Utc};
use serde_json::Value;
use sqlx::postgres::types::{PgInterval, PgRange, PgTimeTz};
use sqlx::types::BigDecimal;
use uuid::Uuid;

rqb::schema! {
    table sample.app_users {
        id: uuid = Uuid,
        organization_id: uuid = Uuid,
        email: text = String,
        status: text = String,
        display_name: text = String,
        active: bool = bool,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.events {
        id: uuid = Uuid,
        order_id: uuid = Uuid,
        event_type: text = String,
        payload: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.invoices {
        id: uuid = Uuid,
        invoice_no: int8 = i64,
        customer_id: uuid = Uuid,
        state: invoice_state,
        amount: numeric = BigDecimal,
        tax_rate: numeric = BigDecimal,
        amount_history: "numeric[]" = Vec<BigDecimal>,
        due_on: date = NaiveDate,
        issued_at: timestamp = NaiveDateTime,
        paid_at: timestamptz = DateTime<Utc>,
        reminder_time: time = NaiveTime,
        cutoff_time: timetz = PgTimeTz<NaiveTime, FixedOffset>,
        grace_period: interval = PgInterval,
        service_days: daterange = PgRange<NaiveDate>,
        billing_window: tstzrange = PgRange<DateTime<Utc>>,
        client_ip: inet = String,
        client_network: cidr = String,
        pdf: bytea = Vec<u8>,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
    }
    table sample.order_items {
        id: uuid = Uuid,
        order_id: uuid = Uuid,
        product_id: uuid = Uuid,
        quantity: int4 = i32,
        unit_price_cents: int8 = i64,
        line_total_cents: int8 = i64,
        metadata: jsonb = Value,
    }
    view sample.order_search_view {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        organization_id: uuid = Uuid,
        organization_slug: text = String,
        user_email: text = String,
        status: text = String,
        total_cents: int8 = i64,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        item_count: int8 = i64,
        event_count: int8 = i64,
        last_event_at: timestamptz = DateTime<Utc>,
    }
    table sample.orders {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        status: text = String,
        total_cents: int8 = i64,
        metadata: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.organizations {
        id: uuid = Uuid,
        slug: text = String,
        name: text = String,
        settings: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.products {
        id: uuid = Uuid,
        sku: text = String,
        name: text = String,
        price_cents: int8 = i64,
        attributes: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
    }
}
