// @generated by rqb-cli. Do not edit by hand.

//! Generated rqb schema metadata.
//!
//! Relation modules expose typed fields, relation sources, alias handles, and
//! unique constraint names for use with the `rqb` query builder.

#![allow(dead_code)]

use chrono::{DateTime, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, Utc};
use serde_json::Value;
use sqlx::postgres::types::{PgInterval, PgRange, PgTimeTz};
use sqlx::types::BigDecimal;
use uuid::Uuid;

/// Rust mapping for PostgreSQL enum `sample.invoice_state`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, sqlx::Type)]
#[sqlx(type_name = "sample.invoice_state")]
pub enum InvoiceState {
    /// PostgreSQL enum label `draft`.
    #[sqlx(rename = "draft")]
    Draft,
    /// PostgreSQL enum label `issued`.
    #[sqlx(rename = "issued")]
    Issued,
    /// PostgreSQL enum label `paid`.
    #[sqlx(rename = "paid")]
    Paid,
    /// PostgreSQL enum label `void`.
    #[sqlx(rename = "void")]
    Void,
}

rqb::schema! {
    table sample.app_users {
        id: uuid = Uuid,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        organization_id: uuid = Uuid,
        email: text = String,
        status: text = String,
        display_name: text = String,
        active: bool = bool,
        created_at: timestamptz = DateTime<Utc>,
        constraints {
            APP_USERS_EMAIL_KEY: "app_users_email_key",
            APP_USERS_ORGANIZATION_EMAIL_KEY: "app_users_organization_email_key",
            APP_USERS_PKEY: "app_users_pkey",
        }
    }
    table sample.events {
        id: uuid = Uuid,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        order_id: uuid = Uuid,
        event_type: text = String,
        payload: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        constraints {
            EVENTS_PKEY: "events_pkey",
        }
    }
    table sample.invoices {
        id: uuid = Uuid,
        // Identity: always. Do not include in INSERT assignments; use OVERRIDING SYSTEM VALUE to override.
        invoice_no: int8 = i64,
        customer_id: uuid = Uuid,
        state: "sample.invoice_state" = InvoiceState,
        amount: numeric = BigDecimal,
        tax_rate: numeric = BigDecimal,
        amount_history: "numeric[]" = Vec<BigDecimal>,
        due_on: date = NaiveDate,
        issued_at: timestamp = NaiveDateTime,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        paid_at: timestamptz = DateTime<Utc>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        reminder_time: time = NaiveTime,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        cutoff_time: timetz = PgTimeTz<NaiveTime, FixedOffset>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        grace_period: interval = PgInterval,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        service_days: daterange = PgRange<NaiveDate>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        billing_window: tstzrange = PgRange<DateTime<Utc>>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        client_ip: inet = String,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        client_network: cidr = String,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        pdf: bytea = Vec<u8>,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
        constraints {
            INVOICES_INVOICE_NO_KEY: "invoices_invoice_no_key",
            INVOICES_PKEY: "invoices_pkey",
        }
    }
    table sample.order_items {
        id: uuid = Uuid,
        order_id: uuid = Uuid,
        product_id: uuid = Uuid,
        quantity: int4 = i32,
        unit_price_cents: int8 = i64,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        // Generated: stored. Do not include in INSERT assignments.
        line_total_cents: int8 = i64,
        metadata: jsonb = Value,
        constraints {
            ORDER_ITEMS_ORDER_PRODUCT_KEY: "order_items_order_product_key",
            ORDER_ITEMS_PKEY: "order_items_pkey",
        }
    }
    // View column nullability is conservative in Postgres metadata.
    view sample.order_search_view {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        organization_id: uuid = Uuid,
        organization_slug: text = String,
        user_email: text = String,
        status: text = String,
        total_cents: int8 = i64,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        item_count: int8 = i64,
        event_count: int8 = i64,
        last_event_at: timestamptz = DateTime<Utc>,
    }
    table sample.orders {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        status: text = String,
        total_cents: int8 = i64,
        metadata: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
        constraints {
            ORDERS_PKEY: "orders_pkey",
        }
    }
    table sample.organizations {
        id: uuid = Uuid,
        slug: text = String,
        name: text = String,
        settings: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        constraints {
            ORGANIZATIONS_PKEY: "organizations_pkey",
            ORGANIZATIONS_SLUG_KEY: "organizations_slug_key",
        }
    }
    table sample.products {
        id: uuid = Uuid,
        sku: text = String,
        name: text = String,
        price_cents: int8 = i64,
        attributes: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
        constraints {
            PRODUCTS_PKEY: "products_pkey",
            PRODUCTS_SKU_KEY: "products_sku_key",
        }
    }
}
