// @generated by rqb-cli. Do not edit by hand.

#![allow(dead_code)]

use chrono::{DateTime, FixedOffset, NaiveDate, NaiveDateTime, NaiveTime, Utc};
use serde_json::Value;
use sqlx::postgres::types::{PgInterval, PgRange, PgTimeTz};
use sqlx::types::BigDecimal;
use uuid::Uuid;

#[derive(Clone, Copy, Debug, PartialEq, Eq, sqlx::Type)]
#[sqlx(type_name = "sample.invoice_state")]
pub enum InvoiceState {
    #[sqlx(rename = "draft")]
    Draft,
    #[sqlx(rename = "issued")]
    Issued,
    #[sqlx(rename = "paid")]
    Paid,
    #[sqlx(rename = "void")]
    Void,
}

rqb::schema! {
    table sample.app_users {
        id: uuid = Uuid,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        organization_id: uuid = Uuid,
        email: text = String,
        status: text = String,
        display_name: text = String,
        active: bool = bool,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.events {
        id: uuid = Uuid,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        order_id: uuid = Uuid,
        event_type: text = String,
        payload: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.invoices {
        id: uuid = Uuid,
        // Identity: always. Do not include in INSERT assignments; use OVERRIDING SYSTEM VALUE to override.
        invoice_no: int8 = i64,
        customer_id: uuid = Uuid,
        state: "sample.invoice_state" = InvoiceState,
        amount: numeric = BigDecimal,
        tax_rate: numeric = BigDecimal,
        amount_history: "numeric[]" = Vec<BigDecimal>,
        due_on: date = NaiveDate,
        issued_at: timestamp = NaiveDateTime,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        paid_at: timestamptz = DateTime<Utc>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        reminder_time: time = NaiveTime,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        cutoff_time: timetz = PgTimeTz<NaiveTime, FixedOffset>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        grace_period: interval = PgInterval,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        service_days: daterange = PgRange<NaiveDate>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        billing_window: tstzrange = PgRange<DateTime<Utc>>,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        client_ip: inet = String,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        client_network: cidr = String,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        pdf: bytea = Vec<u8>,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
    }
    table sample.order_items {
        id: uuid = Uuid,
        order_id: uuid = Uuid,
        product_id: uuid = Uuid,
        quantity: int4 = i32,
        unit_price_cents: int8 = i64,
        // Nullable in Postgres metadata. Use Option<T> in row structs.
        // Generated: stored. Do not include in INSERT assignments.
        line_total_cents: int8 = i64,
        metadata: jsonb = Value,
    }
    // View column nullability is conservative in Postgres metadata.
    view sample.order_search_view {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        organization_id: uuid = Uuid,
        organization_slug: text = String,
        user_email: text = String,
        status: text = String,
        total_cents: int8 = i64,
        tags: "text[]" = Vec<String>,
        metadata: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
        item_count: int8 = i64,
        event_count: int8 = i64,
        last_event_at: timestamptz = DateTime<Utc>,
    }
    table sample.orders {
        id: uuid = Uuid,
        user_id: uuid = Uuid,
        status: text = String,
        total_cents: int8 = i64,
        metadata: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.organizations {
        id: uuid = Uuid,
        slug: text = String,
        name: text = String,
        settings: jsonb = Value,
        created_at: timestamptz = DateTime<Utc>,
    }
    table sample.products {
        id: uuid = Uuid,
        sku: text = String,
        name: text = String,
        price_cents: int8 = i64,
        attributes: jsonb = Value,
        tags: "text[]" = Vec<String>,
        created_at: timestamptz = DateTime<Utc>,
    }
}
