[package]
name = "rqb-sample-raw-query"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
rqb = { path = "../../crates/rqb" }
rqb-sample-schema = { path = "../schema" }
sqlx = { version = "0.8.6", default-features = false, features = ["postgres", "uuid", "runtime-tokio-rustls"] }
uuid = "1"
