[package]
name = "rqb-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Schema introspection and code generation for rqb."
keywords = ["postgres", "query-builder", "codegen", "database", "cli"]
categories = ["database", "command-line-utilities", "development-tools"]
publish = false

[[bin]]
name = "rqb"
path = "src/main.rs"
doc = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
heck.workspace = true
sqlx.workspace = true
syn = { workspace = true, features = ["full", "parsing"] }
tokio.workspace = true
